services:
  thinkbigg-postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: thinkbigg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thinkbigg-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  thinkbigg-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: thinkbigg-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@thinkbigg-postgres:5432/${POSTGRES_DB}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      thinkbigg-postgres:
        condition: service_healthy
    networks:
      - thinkbigg-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  thinkbigg-network:
    driver: bridge
