version: '3.8'

services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: thinkbigg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thinkbigg-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  nextjs:
    build:
      context: ./thinkbigg-dev
      dockerfile: Dockerfile
    container_name: thinkbigg-nextjs
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - thinkbigg-network

networks:
  thinkbigg-network:
    driver: bridge

volumes:
  postgres_data: 